import {
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  Sidebar,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { File, FileText, Home, Inbox, InfoIcon } from "lucide-react";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const items = [
    {
      title: "Home",
      url: "./",
      icon: Home,
    },
    {
      title: "Contact us",
      url: "/contact-us",
      icon: Inbox,
    },
    {
      title: "FAQ",
      url: "/faq",
      icon: InfoIcon,
    },
    {
      title: "Policy",
      url: "/policy",
      icon: FileText,
    },
    {
      title: "Term and conditions",
      url: "/terms-and-conditions",
      icon: File,
    },
  ];
  return (
    <html lang="en">
      <body className="bg-light-2 dark:bg-dark-2">
        <SidebarProvider>
          <Sidebar>
            <SidebarContent>
              <SidebarGroup>
                <SidebarGroupContent>
                  <SidebarMenu>
                    {items.map((item) => (
                      <SidebarMenuItem key={item.title}>
                        <SidebarMenuButton asChild>
                          <a href={item.url}>
                            <item.icon />
                            <span>{item.title}</span>
                          </a>
                        </SidebarMenuButton>
                      </SidebarMenuItem>
                    ))}
                  </SidebarMenu>
                </SidebarGroupContent>
              </SidebarGroup>
            </SidebarContent>
          </Sidebar>
          <main className="h-full w-screen">
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
